/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    // Dependency for connecting the database to the application
    implementation("com.mysql:mysql-connector-j:9.0.0")

    // Dependency for better UI
    implementation("com.formdev:flatlaf:3.4.1")

    // (Swing X) implementation("com.formdev:flatlaf-swingx:3.4.1")
    implementation("com.formdev:flatlaf-intellij-themes:3.4.1")
}

application {
    // Define the main class for the application.
    mainClass.set("it.unibo.cloudnine.CloudNine")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
